### ISSUE TITLE
Buscar fuentes

### ISSUE THREAD

**Issue by mancusolobo** [pptscdia2021/pp12021grupo2_a1-pp12021grupo2_a1#7]
Determinar fuentes de datos para comparar cotizaciones (además de webscraping y yfinance o yahoofinance) tales como BCRA.

**Comment by BrenHidalgo** [comment]
Fuentes a trabajar:

- Yahoo Finanzas: [https://es-us.finanzas.yahoo.com/mercados/materias-primas/](url)
- Investing.com(Sitio web mundial):  [https://es.investing.com/commodities/real-time-futures](url)
- Matba Rofex SA (Sitio web de Argentina): [http://datacenter.matba.com.ar/ajustesdc.aspx](url)
- Expansion (Sitio web de Madrid) [https://www.expansion.com/mercados/cotizaciones/materias.html](url)
